Repository eclipse-che/che-operator, pull requests merged in 2021-06, with the labels that each got.

#847 fix: Add PVC delete permission to che service account
  deploy/cluster_role.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  pkg/controller/che/workspace_namespace_permission.go
Labels: ok-to-test

#852 ci: Use semantic PRs name in release workflows
  .github/workflows/release-chectl.yml
  make-release.sh
Labels: lgtm

#855 fix: Remove duplicates in related images
  olm/addDigests.sh
Labels: lgtm

#857 fix: Remove NON_PROXY from custom resource in disconnected tests
  .ci/oci-disconnected.sh
Labels: lgtm

#856 fix: dashboard ingress configuration with custom cheHost
  Dockerfile
  deploy/crds/org_v1_che_crd-v1beta1.yaml
  deploy/crds/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  deploy/operator.yaml
  pkg/apis/org/v1/che_types.go
  pkg/apis/org/v1/zz_generated.deepcopy.go
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/identity-provider/identity_provider.go
  pkg/deploy/ingres_test.go
  pkg/deploy/ingress.go
  pkg/deploy/route.go
  pkg/deploy/route_test.go
  templates/keycloak-update.sh
Labels: lgtm

#859 [Selenium] Use 'happy-path' test pod yaml file from che repo
  .ci/oci-devworkspace-happy-path.sh
Labels: lgtm, ok-to-test

#866 fix: Switch to go 1.15 in GitHub Actions
  .ci/openshift-ci/Dockerfile
  .github/workflows/pr-main-check.yml
  .github/workflows/release.yml
  olm/docker-run.sh
  olm/update-resources.sh
Labels: lgtm

#860 Add support for configuring the labels for gateway configmaps
  pkg/apis/org/conversion.go
  pkg/apis/org/conversion_test.go
  pkg/apis/org/v2alpha1/checluster.go
Labels: lgtm

#870 fix: rename CheClusterStatus structure to bypass bug in operator-sdk
  pkg/apis/org/v1/che_types.go
  pkg/apis/org/v2alpha1/checluster.go
  pkg/apis/org/v2alpha1/zz_generated.deepcopy.go
Labels: lgtm

#876 chore: eclipse/che#19762 - can't use ubi8-minimal:8.4 and then install golang as Brew builds fail
  Dockerfile
Labels: lgtm

#875 Update scripts to handle chebackupserverconfigurations CRD
  .github/bin/check-resources.sh
  deploy.sh
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/csv-config.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/csv-config.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  local-debug.sh
  make-release.sh
  olm/prepare-community-operators-update.sh
  olm/release-olm-files.sh
  olm/update-resources.sh
Labels: lgtm

#877 fix: Fix image puller reconcile infinite loop when checluster image puller deployment name and configmap name are empty
  pkg/deploy/kubernetes_image_puller.go
Labels: lgtm

#878 fix: [Backport] Fix image puller reconcile infinite loop when checluster image puller deployment name and configmap name are empty #877
  pkg/deploy/kubernetes_image_puller.go
Labels: lgtm
