Repository eclipse-che/che-operator, pull requests merged in 2021-05, with the labels that each got.

#809 [Selenium] Stabilize happy-path test, add devworkspace logs to test report
  .ci/oci-devworkspace-happy-path.sh
  .ci/openshift-ci/happy-path-che.yaml
Labels: lgtm, ok-to-test

#816 Fix release script to check resources only once
  .github/workflows/release.yml
  make-release.sh
Labels: lgtm, needs-ok-to-test

#821 Correctly update dashboard image tag
  olm/release-olm-files.sh
Labels: lgtm, needs-ok-to-test

#825 Minor fix in prepare-community-operators-update.sh
  olm/prepare-community-operators-update.sh
Labels: lgtm

#811 Che Operator Security Context Defined Posture Parameters
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  olm/update-resources.sh
Labels: lgtm, ok-to-test

#818 Do not allow to upgrade che 7.31 or later to upgrade installation that configured with namespace strategies other than "per user"
  deploy/crds/org_v1_che_crd-v1beta1.yaml
  deploy/crds/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  pkg/apis/org/v1/che_types.go
  pkg/controller/che/che_controller.go
  pkg/controller/che/che_controller_test.go
  pkg/controller/che/che_cr_validator.go
  pkg/controller/che/workspace_namespace_permission.go
  pkg/deploy/server/che_configmap.go
  pkg/util/util.go
Labels: lgtm

#829 Use OpenShift API internal URL to fetch API certificate
  pkg/controller/che/che_controller.go
Labels: lgtm

#812 Add script to deploy eclipse che in disconnected environment
  .ci/oci-disconnected.sh
  .github/bin/resources/slack-message-template.json
  .github/bin/slack.sh
Labels: lgtm, needs-ok-to-test

#828 [Selenium] Add devworkspace-che logs to test report
  .ci/oci-devworkspace-happy-path.sh
Labels: lgtm

#835 Configure keycloak by setting -Dkeycloak.connectionsHttpClient.default.expect-continue-enabled=true and -Dkeycloak.connectionsHttpClient.default.reuse-connections=false
  pkg/deploy/identity-provider/deployment_keycloak.go
Labels: lgtm

#832 Che Operator updates DWO and DWCO resources
  .ci/cico_updates_openshift.sh
  .ci/oci-multi-host.sh
  .ci/oci-single-host.sh
  .github/bin/common.sh
  Dockerfile
  deploy/cluster_role.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  olm/olm.sh
  pkg/deploy/defaults.go
  pkg/deploy/dev-workspace/dev_workspace.go
  pkg/deploy/dev-workspace/dev_workspace_test.go
  pkg/deploy/sync.go
  pkg/deploy/test_util.go
  pkg/util/test_util.go
  pkg/util/util.go
Labels: needs-ok-to-test

#840 BackPort : Fix dashboard component names depending on che flavor
  pkg/controller/che/che_controller.go
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/dashboard/dashboard_test.go
  pkg/deploy/dashboard/deployment_dashboard.go
Labels: lgtm

#839 Fix dashboard component names depending on che flavor
  pkg/controller/che/che_controller.go
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/dashboard/dashboard_test.go
  pkg/deploy/dashboard/deployment_dashboard.go
Labels: lgtm, ok-to-test

#841 Fix che.properties file links.
  make-release.sh
  olm/update-resources.sh
Labels: lgtm

#842 Add 2h of sleep to do some manual tests
  .ci/oci-disconnected.sh
Labels: lgtm

#848 chore(Dockerfile): Switch to go 1.15
  Dockerfile
  go.mod
  olm/update-resources.sh
  vendor/modules.txt
Labels: lgtm
