Repository eclipse-che/che-operator, pull requests merged in 2021-04, with the labels that each got.

#749 Minor: Add GOROOT check for dev scripts.
  olm/update-crd-files.sh
  olm/update-nightly-bundle.sh
Labels: lgtm

#739 Change default pvc to 10G.
  deploy/crds/org_v1_che_cr.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  pkg/controller/che/che_controller.go
  pkg/deploy/defaults.go
  pkg/deploy/pvc.go
Labels: lgtm

#756 Improve reconciling crb finalizers
  deploy/cluster_role_binding.yaml
  deploy/namespaces_cluster_role_binding.yaml
  pkg/controller/che/che_controller.go
  pkg/deploy/clusterrolebinding.go
  pkg/deploy/clusterrolebinding_test.go
  pkg/deploy/finalizer.go
  pkg/deploy/finalizer_test.go
Labels: lgtm

#757 Use v1beta1 api for the chemanager crd.
  Dockerfile
  cmd/manager/main.go
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/deploy/dev-workspace/dev_workspace.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/modules.txt
Labels: lgtm

#753 Code clean up 3
  .github/workflows/minishift-e2e.yaml
  deploy.sh
  deploy/role_binding_oauth.yaml
  e2e/config.go
  e2e/create.go
  e2e/delete.go
  e2e/deserialize.go
  e2e/get.go
  e2e/patch.go
  e2e/run_tests.sh
  e2e/tests.go
  e2e/watch.go
  pkg/controller/che/che_controller.go
  pkg/controller/che/create.go
  pkg/controller/che/oauth_initial_htpasswd_provider.go
  pkg/controller/che/workspace_namespace_permission.go
  pkg/deploy/data_types.go
  pkg/deploy/deployment.go
  pkg/deploy/devfile-registry/devfile_registry.go
  pkg/deploy/expose/expose.go
  pkg/deploy/identity-provider/identity_provider.go
  pkg/deploy/oauthclient.go
  pkg/deploy/plugin-registry/plugin_registry.go
  pkg/deploy/postgres/postgres.go
  pkg/deploy/postgres/postgres_test.go
  pkg/deploy/route.go
  pkg/deploy/route_test.go
  pkg/deploy/secret.go
  pkg/deploy/sercet_test.go
  pkg/deploy/server/che_configmap.go
  pkg/deploy/server/che_service_test.go
  pkg/deploy/server/service.go
  pkg/deploy/service.go
  pkg/deploy/service_account.go
  pkg/deploy/service_test.go
  pkg/deploy/sync.go
  pkg/deploy/tls.go
Labels: lgtm

#758 Allow to trigger image build manually
  .github/workflows/nightly-image-build.yaml
Labels: lgtm

#762 Add GitHub action to validate source code
  .github/workflows/build.yml
  .github/workflows/check-nightly-olm-bundle-version.yaml
  .github/workflows/check-nightly-olm-bundle.yaml
  .github/workflows/pr-check.yml
  mocks/permission_checker_mock.go
  mocks/pkg/controller/che/oauth_initial_htpasswd_provider_mock.go
  mocks/pkg/util/process_mock.go
  pkg/controller/add_che.go
  pkg/controller/che/che_controller_test.go
  pkg/controller/controller.go
  pkg/deploy/dev-workspace/dev_workspace.go
  pkg/deploy/sync.go
  pkg/util/k8s_helpers_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm

#766 Fix getting exposure strategy in case of k8s
  pkg/controller/che/che_controller.go
  pkg/deploy/expose/expose.go
  pkg/deploy/gateway/gateway.go
  pkg/deploy/ingress.go
  pkg/deploy/server/che_configmap.go
  pkg/deploy/server/che_configmap_test.go
Labels: lgtm

#765 Fix che operator single-host tests by adding devworkspace templates to chectl command
  .github/bin/common.sh
Labels: lgtm

#767 Update to traefik 2.3.2 using new quay.io image
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: lgtm

#761 Code clean up 4
  pkg/controller/che/che_controller.go
  pkg/deploy/data_types.go
  pkg/deploy/devfile-registry/devfile_registry.go
  pkg/deploy/devfileregistry/devfileregistry.go
  pkg/deploy/devfileregistry/devfileregistry_configmap.go
  pkg/deploy/devfileregistry/devfileregistry_deployment.go
  pkg/deploy/devfileregistry/devfileregistry_deployment_test.go
  pkg/deploy/devfileregistry/devfileregistry_test.go
  pkg/deploy/devfileregistry/init_test.go
  pkg/deploy/identity-provider/identity_provider.go
  pkg/deploy/plugin-registry/plugin_registry.go
  pkg/deploy/pluginregistry/init_test.go
  pkg/deploy/pluginregistry/pluginregistry.go
  pkg/deploy/pluginregistry/pluginregistry_configmap.go
  pkg/deploy/pluginregistry/pluginregistry_deployment.go
  pkg/deploy/pluginregistry/pluginregistry_deployment_test.go
  pkg/deploy/pluginregistry/pluginregistry_test.go
  pkg/deploy/postgres/postgres.go
  pkg/deploy/postgres/postgres_deployment.go
  pkg/deploy/postgres/postgres_test.go
  pkg/deploy/registry/registry_deployment.go
  pkg/deploy/server/che_configmap.go
  pkg/deploy/server/che_configmap_test.go
Labels: lgtm

#770 to build in brew, and to be able to update...
  Dockerfile
Labels: lgtm

#771 Fix creating che ingress with correct host
  pkg/controller/che/che_controller.go
Labels: lgtm

#777 Fix GOROOT env variable not being set during release
  .github/workflows/release.yml
  olm/update-crd-files.sh
  olm/update-nightly-bundle.sh
Labels: lgtm

#784 Replace references from master to main branches
  .ci/README.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/bin/check-nightly-olm-bundle-version.sh
  .github/workflows/build-and-push-catalog-and-bundle-images.yaml
  .github/workflows/check-nightly-olm-bundle.yaml
  .github/workflows/minikube-operator-update.yaml
  .github/workflows/minishift-operator-update.yaml
  .github/workflows/release-che-docs.yml
  .github/workflows/release-chectl.yml
  .github/workflows/release-community-operator-PRs.yml
  README.md
  RELEASE.md
  devfile.yaml
  make-release.sh
  pkg/deploy/defaults.go.update.sh
Labels: lgtm

#787 move ci.yaml template out of the prepare-community-operators-update.sh script so it's a standalone file; add notes about update process and why we have this file
  olm/ci.yaml
  olm/prepare-community-operators-update.sh
Labels: lgtm

#769 Remove OpenShift OAuth user when Eclipse Che is removed
  deploy/crds/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  pkg/apis/org/v1/che_types.go
  pkg/controller/che/che_controller.go
  pkg/controller/che/oauth_initial_htpasswd_provider.go
  pkg/controller/che/oauth_initial_htpasswd_provider_test.go
  pkg/deploy/sync.go
  pkg/util/util.go
Labels: lgtm

#789 Fix DWO deployment in minikube
  Dockerfile
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/che/che_controller.go
  pkg/deploy/consolelink.go
  pkg/deploy/dev-workspace/dev_workspace.go
  pkg/deploy/dev-workspace/dev_workspace_test.go
  pkg/util/util.go
Labels: ok-to-test

#791 Make happy path tests to use latest templates from PR
  .ci/oci-devworkspace-happy-path.sh
Labels: lgtm, ok-to-test

#684 Run dashboard as separate deployment
  .github/workflows/pr-check.yml
  deploy/crds/org_v1_che_crd-v1beta1.yaml
  deploy/crds/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  deploy/operator.yaml
  make-release.sh
  olm/release-olm-files.sh
  pkg/apis/org/v1/che_types.go
  pkg/controller/che/che_controller.go
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/dashboard/dashboard_deployment_test.go
  pkg/deploy/dashboard/dashboard_test.go
  pkg/deploy/dashboard/deployment_dashboard.go
  pkg/deploy/dashboard/init_test.go
  pkg/deploy/defaults.go
  pkg/deploy/defaults_test.go
  replace-images-tags.sh
Labels: ok-to-test

#792 Update GitHub workflows
  .github/bin/check-bundle-version.sh
  .github/bin/check-nightly-olm-bundle.sh
  .github/bin/check-resources.sh
  .github/bin/common.sh
  .github/bin/minishift/test-operator-update.sh
  .github/bin/minishift/test-operator.sh
  .github/workflows/build-catalog-and-bundle-images.yaml
  .github/workflows/build-nightly-images.yaml
  .github/workflows/check-nightly-olm-bundle-version.yaml
  .github/workflows/check-nightly-olm-bundle.yaml
  .github/workflows/minishift-operator-update.yaml
  .github/workflows/minishift-operator.yaml
  .github/workflows/minishift-stable-operator-update.yaml
  .github/workflows/pr-check.yml
  .github/workflows/pr-main-check.yml
  .github/workflows/release.yml
  .vscode/tasks.json
  README.md
  RELEASE.md
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  make-release.sh
  olm/README.md
  olm/update-crd-files.sh
  olm/update-nightly-bundle.sh
  olm/update-resources.sh
  replace-images-tags.sh
Labels: needs-ok-to-test

#799 Copy 7.29.1 csv to main
  deploy/olm-catalog/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml.diff
  deploy/olm-catalog/stable/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml.diff
  deploy/olm-catalog/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
  deploy/olm-catalog/stable/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml.diff
  version/version.go
Labels: ok-to-test

#800 Add `/auth` path to external identity providers url
  pkg/deploy/server/che_configmap.go
  pkg/deploy/server/che_configmap_test.go
Labels: ok-to-test

#786 Fix redirect URL-s for Che-public client to allow factory redirects;
  Dockerfile
  local-debug.sh
  pkg/deploy/identity-provider/exec.go
  pkg/deploy/identity-provider/identity_provider.go
  templates/keycloak-provision.sh
  templates/keycloak-update.sh
Labels: lgtm, ok-to-test

#805 fix: Add common selector for che-dashboard
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/dashboard/dashboard_test.go
  pkg/deploy/dashboard/deployment_dashboard.go
Labels: ok-to-test

#793 Add metrics role to the cluster role
  README.md
  deploy/cluster_role.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  pkg/controller/che/workspace_namespace_permission.go
Labels: ok-to-test

#810 Expose Che route on / path to avoid HostAlreadyClaimed error
  pkg/controller/che/che_controller.go
Labels: lgtm, ok-to-test
