Repository eclipse-che/che-operator, pull requests merged in 2021-07, with the labels that each got.

#879 Build restic binary from source
  Dockerfile
Labels: lgtm

#885 fix: Some tests in minikube in version 1.18.1 is failing.
  .ci/oci-proxy.sh
  .github/bin/common.sh
  .github/workflows/minikube-backup-restore.yaml
  .github/workflows/minikube-olm.yaml
  .github/workflows/minikube-operator-singlehost.yaml
  .github/workflows/minikube-operator-update.yaml
  .github/workflows/minikube-stable-olm-update.yaml
Labels: lgtm

#887 fix: [Backport] Fix image puller reconcile infinite loop when checluster image puller deployment name and configmap name are empty
  pkg/deploy/kubernetes_image_puller.go
Labels: lgtm

#745 feat: Run DWCO and CO in a same pod but different containers
  .github/bin/check-resources.sh
  Dockerfile
  cmd/manager/main.go
  deploy.sh
  deploy/cluster_role.yaml
  deploy/crds/chemanagers.che.eclipse.org.CustomResourceDefinition.yaml
  deploy/crds/devworkspaceroutings.controller.devfile.io.CustomResourceDefinition.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/build-roles.sh
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/csv-config.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/build-roles.sh
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/csv-config.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/proxy_cluster_role.yaml
  deploy/proxy_cluster_role_binding.yaml
  deploy/role.yaml
  local-debug.sh
  make-release.sh
  olm/buildOLMBundlesFromReleaseManifestFiles.sh
  olm/release-olm-files.sh
  olm/update-resources.sh
  pkg/apis/org/conversion_test.go
  pkg/deploy/dev-workspace/dev_workspace.go
  pkg/deploy/dev-workspace/dev_workspace_test.go
  pkg/util/util.go
  replace-images-tags.sh
Labels: ok-to-test

#861 feat: native user authentication
  deploy/cluster_role.yaml
  deploy/crds/org_v1_che_crd-v1beta1.yaml
  deploy/crds/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  deploy/operator.yaml
  pkg/apis/org/v1/che_types.go
  pkg/apis/org/v1/zz_generated.deepcopy.go
  pkg/controller/che/che_controller.go
  pkg/controller/che/create.go
  pkg/controller/che/gateway_permission.go
  pkg/deploy/defaults.go
  pkg/deploy/gateway/gateway.go
  pkg/deploy/gateway/gateway_test.go
  pkg/deploy/gateway/init_test.go
  pkg/deploy/identity-provider/identity_provider.go
  pkg/deploy/oauthclient.go
  pkg/deploy/server/server_deployment.go
  pkg/util/util.go
Labels: lgtm

#882 fix: Update --push-olm-bundles documentation
  RELEASE.md
  make-release.sh
Labels: lgtm, needs-ok-to-test

#893 feat: Add RELATED_IMAGES environment variables to operator.yaml on release
  olm/addDigests.sh
  olm/license.txt
  olm/release-olm-files.sh
Labels: lgtm

#896 fix: typo - redundant pipe in yq series of commands
  make-release.sh
Labels: lgtm

#898 fix: copy backup/restore CRDs into a stable olm bundle
  olm/release-olm-files.sh
Labels: lgtm

#902 fix: use proper DWO and DWCO versions in release scripts
  make-release.sh
Labels: lgtm

#905 ci: Release script fixes
  make-release.sh
  olm/release-olm-files.sh
Labels: lgtm

#906 fix: more DWCO version fixes in release scripts
  make-release.sh
  olm/release-olm-files.sh
Labels: lgtm

#907 fix: fix wrong variable name in the release script
  make-release.sh
Labels: lgtm

#908 fix: fix wrong variable name in the release script
  make-release.sh
Labels: lgtm

#911 fix: Fix setting image digests on release
  olm/buildDigestMap.sh
  olm/images.sh
Labels: lgtm

#912 fix: fix CSV generation during release
  make-release.sh
  olm/release-olm-files.sh
Labels: lgtm

#915 fix: adding image digests
  olm/buildDigestMap.sh
Labels: lgtm

#916 fix: make che operator take into account DWO Service
  pkg/deploy/dev-workspace/dev_workspace.go
Labels: lgtm

#880 feat: set RELATED_IMAGES images to image puller spec
  deploy/crds/org_v1_che_crd-v1beta1.yaml
  deploy/crds/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  pkg/apis/org/v1/che_types.go
  pkg/controller/che/che_controller_test.go
  pkg/deploy/kubernetes_image_puller.go
  vendor/github.com/che-incubator/kubernetes-image-puller-operator/pkg/apis/che/v1alpha1/kubernetesimagepuller_types.go
Labels: lgtm, needs-ok-to-test

#924 chore(che_types.go): Fix `pvcClaimSize` description
  deploy/crds/org_v1_che_crd-v1beta1.yaml
  deploy/crds/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  pkg/apis/org/v1/che_types.go
Labels: bug, enhancement, lgtm

#923 chore: download restic in zip format instead of using git clone
  Dockerfile
Labels: lgtm

#928 fix: setting keycloak system properties for rh-sso
  pkg/deploy/identity-provider/deployment_keycloak.go
Labels: lgtm

#929 fix: Backport fixes found during che-operator 7.33.0 release
  olm/olm.sh
  pkg/controller/che/che_controller_test.go
Labels: lgtm

#939 chore: CRW-1956 - combine and clean up curl...
  Dockerfile
Labels: lgtm

#942 feat: Improve community operator scripts
  .github/workflows/release-community-operator-PRs.yml
  olm/prepare-community-operators-update.sh
Labels: lgtm

#946 build: CRW-1956 collect zips and restic...
  Dockerfile
Labels: lgtm

#949 feat: Add ability to rebuild OLM images manully
  .github/workflows/build-catalog-and-bundle-images.yaml
Labels: lgtm

#944 build: update to latest traefik image
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm

#950 fix: Reuse ServiceDefaultDiffOpts for gateway service
  pkg/deploy/gateway/gateway.go
Labels: lgtm

#943 chore: Change Devworkspace Che Operator image
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  olm/release-olm-files.sh
Labels: lgtm

#952 chore(manager.yaml): revert traefik image from RC to a stable one
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm

#941 fix: Don't ignore restore status error. I hope it will make restore feature more stable.
  controllers/checlusterrestore/backup_data_restorer.go
Labels: lgtm

#936 feat: ask confirmation if ingress domain does not correspond the current cluster
  Makefile
Labels: lgtm

#954 fix: Fix tear down olm channels
  olm/buildAndPushBundleImages.sh
  olm/olm.sh
Labels: lgtm

#938 feat: Traefik plugin
  .gitignore
  Dockerfile
  api/v1/checluster_types.go
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  config/crd/bases/org_v1_che_crd-v1beta1.yaml
  config/crd/bases/org_v1_che_crd.yaml
  config/manager/manager.yaml
  pkg/deploy/defaults.go
  pkg/deploy/gateway/gateway.go
  pkg/deploy/gateway/gateway_test.go
Labels: lgtm

#937 feat: add an ability to add localhost to allows list for keycloak
  controllers/che/checluster_controller.go
  pkg/deploy/deployment.go
  pkg/deploy/deployment_test.go
  templates/keycloak-provision.sh
  templates/keycloak-update.sh
Labels: lgtm

#955 fix: Add OLM channels recovery script.
  .github/bin/recovery-olm-channels.sh
  .github/workflows/recovery-index-images.yaml
Labels: lgtm

#957 fix: Make CRD file compatible with OpenShift 3.11
  Makefile
  config/crd/bases/org.eclipse.che_checlusterrestores_crd-v1beta1.yaml
Labels: lgtm

#932 fix: Allow roles update for che workspace cluster role
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/rbac/cluster_role.yaml
  controllers/che/workspace_namespace_permission.go
Labels: lgtm

#959 fix: Fail update tests if bundle contains only one bundle.
  olm/testUpdate.sh
Labels: lgtm

#958 chore(debug): Improve debug UX
  Makefile
Labels: lgtm

#961 fix: Make CRDs compatible with OpenShift 3.11
  Makefile
  config/crd/bases/org.eclipse.che_chebackupserverconfigurations_crd-v1beta1.yaml
  config/crd/bases/org.eclipse.che_checlusterbackups_crd-v1beta1.yaml
  config/crd/bases/org_v1_che_crd-v1beta1.yaml
Labels: lgtm

#962 ci: Copy 7.33.2 to main
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  version/version.go
Labels: lgtm

#967 fix: Remove previous RELATED_IMAGES before adding new ones
  olm/addDigests.sh
  olm/release-olm-files.sh
Labels: lgtm, needs-ok-to-test

#969 chore: bump to action-mattermost-notify@1.1.0 (1.0.2 is broken)
  .github/workflows/release.yml
Labels: lgtm

#973 feat: Add infrastructure features labels
  Makefile
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/manifests/bases/che-operator.clusterserviceversion.yaml
Labels: lgtm
