Repository eclipse-che/che-operator, pull requests merged in 2021-12, with the labels that each got.

#1203 feat: Add stable helm chart and gh action to release it.
  .github/workflows/release-helm-charts.yaml
  Makefile
  helmcharts/next/Chart.yaml
  helmcharts/next/README.md
  helmcharts/next/crds/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  helmcharts/next/crds/org.eclipse.che_checlusterbackups_crd.yaml
  helmcharts/next/crds/org.eclipse.che_checlusterrestores_crd.yaml
  helmcharts/next/crds/org_v1_che_crd.yaml
  helmcharts/next/templates/cluster_role.yaml
  helmcharts/next/templates/cluster_rolebinding.yaml
  helmcharts/next/templates/manager.yaml
  helmcharts/next/templates/namespace.yaml
  helmcharts/next/templates/org.eclipse.che_v1_checluster.yaml
  helmcharts/next/templates/role.yaml
  helmcharts/next/templates/role_binding.yaml
  helmcharts/next/templates/service_account.yaml
  helmcharts/next/values.yaml
  helmcharts/stable/Chart.yaml
  helmcharts/stable/README.md
  helmcharts/stable/crds/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  helmcharts/stable/crds/org.eclipse.che_checlusterbackups_crd.yaml
  helmcharts/stable/crds/org.eclipse.che_checlusterrestores_crd.yaml
  helmcharts/stable/crds/org_v1_che_crd.yaml
  helmcharts/stable/templates/cluster_role.yaml
  helmcharts/stable/templates/cluster_rolebinding.yaml
  helmcharts/stable/templates/manager.yaml
  helmcharts/stable/templates/namespace.yaml
  helmcharts/stable/templates/org.eclipse.che_v1_checluster.yaml
  helmcharts/stable/templates/role.yaml
  helmcharts/stable/templates/role_binding.yaml
  helmcharts/stable/templates/service_account.yaml
  helmcharts/stable/values.yaml
  make-release.sh
Labels: needs-ok-to-test

#1208 Fix helm release package action.
  .github/workflows/release-helm-charts.yaml
Labels: lgtm

#1209 Fix helm package release.
  .github/workflows/release-helm-charts.yaml
Labels: lgtm

#1214 ci: Remove MiniShift GH actions
  .github/workflows/minishift-operator-update.yaml
  .github/workflows/minishift-operator.yaml
  .github/workflows/minishift-stable-operator-update.yaml
Labels: lgtm, needs-ok-to-test

#1213 fix: create DevWorkspace metrics service
  pkg/deploy/dev-workspace/sync.go
Labels: lgtm

#1216 Improve release procedure for helm charts.
  Makefile
  helmcharts/stable/Chart.yaml
  helmcharts/stable/README.md
  helmcharts/stable/crds/org_v1_che_crd.yaml
  helmcharts/stable/templates/cluster_role.yaml
  helmcharts/stable/templates/cluster_rolebinding.yaml
  helmcharts/stable/templates/manager.yaml
  helmcharts/stable/templates/org.eclipse.che_v1_checluster.yaml
  helmcharts/stable/templates/role.yaml
  helmcharts/stable/templates/role_binding.yaml
  helmcharts/stable/templates/service_account.yaml
Labels: lgtm

#1219 Remove namespace templates from Helm chart. Fix Helm chart README.md files.
  helmcharts/next/README.md
  helmcharts/next/templates/namespace.yaml
  helmcharts/stable/README.md
  helmcharts/stable/templates/namespace.yaml
Labels: lgtm

#1223 chore: Update `next` bundle
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/rbac/cluster_role.yaml
  helmcharts/next/templates/cluster_role.yaml
Labels: lgtm

#1212 fix: delegate permissions to `get, list, watch` `pods/log` resources
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/rbac/cluster_role.yaml
  controllers/che/checluster_controller_test.go
  controllers/che/workspace_namespace_permission.go
  helmcharts/next/templates/cluster_role.yaml
  pkg/deploy/role.go
Labels: lgtm

#1230 fix: check if tag exists on remote before...
  make-release.sh
Labels: lgtm

#1229 ci: Release version 7.40.0
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/metadata/annotations.yaml
  bundle/stable/eclipse-che-preview-kubernetes/tests/scorecard/config.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/metadata/annotations.yaml
  bundle/stable/eclipse-che-preview-openshift/tests/scorecard/config.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/metadata/annotations.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/metadata/dependencies.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/tests/scorecard/config.yaml
  config/manager/manager.yaml
  helmcharts/stable/Chart.yaml
  helmcharts/stable/crds/org_v1_che_crd.yaml
  helmcharts/stable/templates/cluster_role.yaml
  helmcharts/stable/templates/cluster_rolebinding.yaml
  helmcharts/stable/templates/manager.yaml
  helmcharts/stable/templates/role.yaml
  helmcharts/stable/templates/role_binding.yaml
  helmcharts/stable/templates/service_account.yaml
  version/version.go
Labels: lgtm

#1228 ci: Copy 7.40.0 csv to main
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/metadata/annotations.yaml
  bundle/stable/eclipse-che-preview-kubernetes/tests/scorecard/config.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  bundle/stable/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml.diff
  bundle/stable/eclipse-che-preview-openshift/metadata/annotations.yaml
  bundle/stable/eclipse-che-preview-openshift/tests/scorecard/config.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/metadata/annotations.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/metadata/dependencies.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/tests/scorecard/config.yaml
  helmcharts/stable/Chart.yaml
  helmcharts/stable/crds/org_v1_che_crd.yaml
  helmcharts/stable/templates/manager.yaml
  version/version.go
Labels: lgtm

#1231 fix: migration for OCP 3.11
  pkg/deploy/migration/on-reconcile-one-time-migration.go
Labels: lgtm

#1217 ci: Don't build kubernetes olm bundle
  .github/bin/check-bundle-version.sh
  .github/bin/check-resources.sh
  .github/bin/minikube/test-stable-olm-update.sh
  .github/bin/minishift/test-stable-operator-update.sh
  .github/workflows/build-catalog-and-bundle-images.yaml
  .github/workflows/minikube-stable-olm-update.yaml
  .github/workflows/minikube-stable-update.yaml
  Makefile
  RELEASE.md
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-kubernetes/bundle.Dockerfile
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator_v1_serviceaccount.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/manager-config_v1_configmap.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/next/eclipse-che-preview-kubernetes/metadata/annotations.yaml
  bundle/next/eclipse-che-preview-kubernetes/tests/scorecard/config.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-kubernetes/bundle.Dockerfile
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/stable/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml.diff
  bundle/stable/eclipse-che-preview-kubernetes/metadata/annotations.yaml
  bundle/stable/eclipse-che-preview-kubernetes/tests/scorecard/config.yaml
  config/platforms/kubernetes/che-operator.clusterserviceversion-description-patch.yaml
  config/platforms/kubernetes/che-operator.clusterserviceversion-name-patch.yaml
  config/platforms/kubernetes/kustomization.yaml
  config/rbac/cluster_role.yaml
  helmcharts/next/templates/cluster_role.yaml
  make-release.sh
  olm/README.md
  olm/olm.sh
  olm/prepare-community-operators-update.sh
  olm/release-olm-files.sh
Labels: needs-ok-to-test

#1202 chore: permissions refactoring
  controllers/che/checluster_controller.go
  controllers/che/checluster_controller_test.go
  controllers/che/gateway_permission.go
  controllers/che/workspace_namespace_permission_test.go
  pkg/deploy/dev-workspace/cache.go
  pkg/deploy/dev-workspace/dev_workspace.go
  pkg/deploy/dev-workspace/dev_workspace_syncer.go
  pkg/deploy/dev-workspace/dev_workspace_syncer_test.go
  pkg/deploy/dev-workspace/dev_workspace_test.go
  pkg/deploy/dev-workspace/dev_workspace_utils.go
  pkg/deploy/rbac/gateway_permissions.go
  pkg/deploy/rbac/init_test.go
  pkg/deploy/rbac/rbac.go
  pkg/deploy/rbac/workspace_permissions.go
  pkg/deploy/rbac/workspace_permissions_test.go
  pkg/util/test_util.go
Labels: lgtm

#1232 feat: Add extra labels to CRDS files.
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations.yaml
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups.yaml
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores.yaml
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  config/crd/kustomization.yaml
  config/crd/patches/extralabels_in_chebackupserverconfigurations.yaml
  config/crd/patches/extralabels_in_checlusterbackups.yaml
  config/crd/patches/extralabels_in_checlusterrestores.yaml
  config/crd/patches/extralabels_in_checlusters.yaml
Labels: lgtm

#1237 feat: Add devfile registry internal URL as environment variable
  pkg/deploy/devfileregistry/devfileregistry_deployment.go
Labels: lgtm

#1239 chore: remove reference to platform when deal with olm bundle
  .ci/cico_updates_openshift.sh
  .github/bin/minikube/test-olm.sh
  .github/workflows/build-catalog-and-bundle-images.yaml
  .vscode/launch.json
  README.md
  RELEASE.md
  make-release.sh
  olm/README.md
  olm/buildCatalog.sh
  olm/testCatalog.sh
  olm/testUpdate.sh
Labels: lgtm

#1246 fix: Remove platform option from creation community operators PR
  .github/workflows/release-community-operator-PRs.yml
Labels: lgtm

#1242 fix: add permission to watch devworkspaces
  pkg/deploy/rbac/workspace_permissions.go
Labels: lgtm

#1247 Make backup / restore of Che installation work with devworkspace mode
  controllers/checlusterbackup/backup_data_collector.go
  controllers/checlusterrestore/backup_data_restorer.go
  controllers/checlusterrestore/restore_context.go
Labels: lgtm

#1251 fix: Adopt dashboard tests to downstream
  pkg/deploy/dashboard/dashboard_deployment_test.go
  pkg/deploy/dashboard/dashboard_test.go
Labels: lgtm

#1252 refactor: Do not reconcile on any error inside finalizers
  controllers/che/checluster_controller.go
  controllers/che/checluster_controller_test.go
  controllers/che/checluster_validator.go
  pkg/deploy/consolelink/consolelink.go
  pkg/deploy/consolelink/consolelink_test.go
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/dashboard/dashboard_test.go
  pkg/deploy/dev-workspace/dev_workspace.go
  pkg/deploy/devfileregistry/devfileregistry.go
  pkg/deploy/gateway/gateway.go
  pkg/deploy/identity-provider/identity_provider_reconciler.go
  pkg/deploy/image-puller/imagepuller.go
  pkg/deploy/image-puller/imagepuller_test.go
  pkg/deploy/migration/on-reconcile-one-time-migration.go
  pkg/deploy/openshift-oauth/openshiftoauth.go
  pkg/deploy/openshift-oauth/openshiftoauth_user.go
  pkg/deploy/openshift-oauth/openshiftoauth_user_test.go
  pkg/deploy/pluginregistry/pluginregistry.go
  pkg/deploy/postgres/postgres.go
  pkg/deploy/rbac/gateway_permissions.go
  pkg/deploy/rbac/rbac.go
  pkg/deploy/rbac/workspace_permissions.go
  pkg/deploy/reconcile_manager.go
  pkg/deploy/reconcile_manager_test.go
  pkg/deploy/server/chehost_reconciler.go
  pkg/deploy/server/default_values_reconciler.go
  pkg/deploy/server/server_reconciler.go
  pkg/deploy/tls/certificates.go
  pkg/deploy/tls/tls_secret.go
Labels: lgtm

#1255 fix: catalog version to deploy on OCP 4.9
  .github/bin/common.sh
Labels: lgtm

#1200 fix: ingress annotation when single-host and gateway exposure
  go.mod
  pkg/deploy/ingres_test.go
  pkg/deploy/ingress.go
  vendor/modules.txt
Labels: needs-ok-to-test

#1267 fix: Update next bundles
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  helmcharts/next/templates/manager.yaml
Labels: lgtm
