Repository eclipse-che/che-operator, pull requests merged in 2021-09, with the labels that each got.

#1044 Add 'Technology Preview' to DevWorkspace Operator section description
  api/v1/checluster_types.go
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  config/crd/bases/org_v1_che_crd-v1beta1.yaml
  config/crd/bases/org_v1_che_crd.yaml
  config/manifests/bases/che-operator.clusterserviceversion.yaml
Labels: lgtm

#1046 Add 'Technology Preview' to DevWorkspace Operator section description
  api/v1/checluster_types.go
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  config/crd/bases/org_v1_che_crd-v1beta1.yaml
  config/crd/bases/org_v1_che_crd.yaml
  config/manifests/bases/che-operator.clusterserviceversion.yaml
Labels: lgtm

#1049 fix: Update permissions
  bundle/nightly/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/rbac/cluster_role.yaml
Labels: lgtm

#1040 fix: Set Che host url in the CR status when Che server deployment is ready
  controllers/che/checluster_controller_test.go
  pkg/deploy/dashboard/deployment_dashboard.go
  pkg/deploy/server/server.go
  pkg/util/util.go
Labels: lgtm

#1050 fix: Update Dockerfile to set devworkspace controller version
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  config/rbac/cluster_role.yaml
  make-release.sh
Labels: lgtm

#1041 feat: Prepare community operators scripts to add new bundles format
  olm/prepare-community-operators-update.sh
Labels: lgtm

#1054 fix: Added the default TCP protocol for che-gateway port
  pkg/deploy/gateway/gateway.go
Labels: lgtm

#1051 feat: Rename `stable-all-namespaces` channel to `tech-preview-stable-all-namespaces`
  .gitignore
  README.md
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/bundle.Dockerfile
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_chebackupserverconfigurations_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterrestores_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml.diff
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/metadata/annotations.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/metadata/dependencies.yaml
  bundle/tech-preview-stable-all-namespaces/eclipse-che-preview-openshift/tests/scorecard/config.yaml
  make-release.sh
  olm/prepare-community-operators-update.sh
  olm/release-olm-files.sh
Labels: lgtm

#1052 fix: Release PR should use stable channel to test operator
  .github/bin/minikube/test-olm.sh
Labels: lgtm

#1056 feat: Deprecate devWorkspace from stable channel
  olm/release-olm-files.sh
Labels: lgtm

#1059 fix: release process
  .github/bin/minikube/test-olm.sh
  make-release.sh
Labels: do-not-merge/work-in-progress

#1043 Drops single-user mode
  README.md
  controllers/che/che_cr_validator.go
  controllers/che/create.go
  pkg/deploy/defaults.go
  pkg/deploy/identity-provider/identity_provider.go
  pkg/deploy/postgres/postgres.go
  pkg/deploy/server/server.go
  pkg/deploy/server/server_configmap.go
  pkg/deploy/server/server_deployment.go
  pkg/deploy/server/server_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm

#1060 Fix devworkspaces gateway rules creation on kubernetes
  controllers/devworkspace/solver/che_routing.go
  controllers/devworkspace/solver/che_routing_test.go
Labels: lgtm

#1015 feat: Update keycloak from 6.0.1 to 15
  .github/bin/common.sh
  api/v1/checluster_types.go
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml
  config/crd/bases/org_v1_che_crd-v1beta1.yaml
  config/crd/bases/org_v1_che_crd.yaml
  config/samples/org.eclipse.che_v1_checluster.yaml
  controllers/devworkspace/solver/che_routing_test.go
  pkg/deploy/identity-provider/deployment_keycloak.go
  pkg/deploy/ingress.go
Labels: lgtm

#1066 fix: don't add intial OpenShift OAuth user if native user mode is on
  controllers/che/checluster_controller.go
Labels: lgtm, ok-to-test

#1061 fix: update regexes for KIP default images
  pkg/deploy/kubernetes_image_puller.go
  pkg/deploy/kubernetes_image_puller_test.go
Labels: lgtm

#1055 Create backup on each update
  api/v1/checlusterbackup_types.go
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/org.eclipse.che_checlusterbackups.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusterbackups.yaml
  config/crd/bases/org.eclipse.che_checlusterbackups_crd-v1beta1.yaml
  config/crd/bases/org.eclipse.che_checlusterbackups_crd.yaml
  controllers/che/backup.go
  controllers/che/backup_test.go
  controllers/che/checluster_controller.go
  controllers/checlusterbackup/checlusterbackup_controller.go
  go.mod
  pkg/deploy/server/server.go
  vendor/modules.txt
Labels: lgtm

#1074 chore: Add chectl template command to deploy Eclipse Che
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm

#1045 feat: secure workspace services
  api/conversion.go
  controllers/devworkspace/defaults/defaults.go
  controllers/devworkspace/solver/che_routing.go
  controllers/devworkspace/solver/che_routing_test.go
  controllers/devworkspace/solver/endpoint_exposer.go
  controllers/devworkspace/solver/solver.go
  pkg/deploy/defaults.go
  pkg/deploy/expose/expose.go
  pkg/deploy/gateway/gateway.go
  pkg/deploy/server/server.go
Labels: lgtm

#1073 Provision internal URLs, CAs and proxy settings into dashboard
  pkg/deploy/dashboard/dashboard_deployment_test.go
  pkg/deploy/dashboard/deployment_dashboard.go
  pkg/deploy/server/server_deployment.go
  pkg/deploy/tls.go
Labels: lgtm

#1071 chore: add more kubernetes image puller regex tests
  pkg/deploy/kubernetes_image_puller_test.go
Labels: lgtm

#1072 fix: internal backup server url
  controllers/checlusterbackup/internal_backup_server.go
  pkg/backup_servers/backup_servers.go
Labels: lgtm

#1076 feat: define routing paths for che-server to improve return http codes
  controllers/devworkspace/solver/che_routing.go
  controllers/devworkspace/solver/che_routing_test.go
  controllers/devworkspace/solver/traefik_config.go
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/devfileregistry/devfileregistry.go
  pkg/deploy/expose/expose.go
  pkg/deploy/gateway/gateway.go
  pkg/deploy/gateway/gateway_test.go
  pkg/deploy/gateway/traefik_config.go
  pkg/deploy/gateway/traefik_config_util.go
  pkg/deploy/gateway/traefik_config_util_test.go
  pkg/deploy/identity-provider/identity_provider.go
  pkg/deploy/pluginregistry/pluginregistry.go
Labels: lgtm

#1089 ci: don't test workspace startup for devworkspace controller due to limited resources
  .github/bin/minikube/test-olm.sh
  .github/bin/minikube/test-operator-singlehost-gateway.sh
  .github/bin/minikube/test-operator-singlehost-native.sh
Labels: lgtm

#1090 Do not automatically backup to internal backup server if it doesn't exist
  controllers/che/backup.go
  controllers/che/checluster_controller.go
Labels: lgtm

#1093 feat: Development: add make compile command.
  .vscode/tasks.json
  Makefile
Labels: lgtm

#1092 fix: rework devworkspace tests to use assert
  Makefile
  pkg/deploy/dev-workspace/dev_workspace_test.go
Labels: lgtm

#1091 fix: Add UPDDATE_PASSWORD action for admin user
  templates/keycloak-provision.sh
Labels: lgtm

#1094 Set the type and immutability of the secret when copying the self-signed-cert to the user's namespace.
  bundle/next-all-namespaces/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next-all-namespaces/eclipse-che-preview-openshift/metadata/annotations.yaml
  bundle/next/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  controllers/usernamespace/controller.go
  controllers/usernamespace/controller_test.go
  controllers/usernamespace/namespacecache.go
Labels: lgtm

#1095 fix: restore process if keycloak is already deleted
  controllers/checlusterrestore/backup_data_restorer.go
Labels: lgtm

#1096 fix: Fixes for operator release and post-release jobs
  .github/workflows/release-chectl.yml
  .github/workflows/release-community-operator-PRs.yml
  .github/workflows/release.yml
Labels: lgtm

#1097 fix: Create backup on every Che update
  controllers/che/checluster_controller.go
Labels: lgtm

#1082 fix: delete KIP finalizer and KIP operator on CheCluster CR delete
  controllers/che/checluster_controller_test.go
  pkg/deploy/defaults.go
  pkg/deploy/kubernetes_image_puller.go
Labels: lgtm

#1098 build: reorganize dockerfile to better utilize cache
  Dockerfile
Labels: lgtm

#1101 fix: remove DWO update from release process
  make-release.sh
Labels: lgtm

#1102 fix: fix release docker build command
  make-release.sh
Labels: lgtm

#1108 ci: fix release
  .ci/cico_updates_openshift.sh
  olm/release-olm-files.sh
Labels: lgtm

#1107 chore: update release runner to ubuntu-20.04
  .github/workflows/release.yml
Labels: lgtm

#1111 ci: fix release process
  make-release.sh
Labels: lgtm
