Repository eclipse-che/che-operator, pull requests merged in 2022-06, with the labels that each got.

#1403 fix: HeaderMessage -> headerMessage, fix scripts
  .ci/openshift-ci/Dockerfile
  api/v2/checluster_types.go
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
  config/crd/bases/org.eclipse.che_checlusters.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  olm/olm.sh
  olm/release-olm-files.sh
Labels: lgtm

#1404 2nd proofreading of api/v2/checluster_types.go (grammar, interpunction, clarity etc.)
  api/v2/checluster_types.go
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
  config/crd/bases/org.eclipse.che_checlusters.yaml
  config/manifests/bases/che-operator.clusterserviceversion.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
Labels: lgtm, needs-ok-to-test

#1400 feat(oauth-proxy): configuration enhancements for k8s config
  api/checluster_conversion_from_test.go
  api/checluster_conversion_to_test.go
  api/checluster_round_conversion_test.go
  api/v1/checluster_conversion_from.go
  api/v1/checluster_conversion_to.go
  api/v1/checluster_types.go
  api/v2/checluster_types.go
  api/v2/checluster_types_test.go
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
  config/crd/bases/org.eclipse.che_checlusters.yaml
  controllers/devworkspace/solver/che_routing.go
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  pkg/common/constants/constants.go
  pkg/common/utils/utils.go
  pkg/common/utils/utils_test.go
  pkg/deploy/dashboard/dashboard.go
  pkg/deploy/gateway/gateway.go
  pkg/deploy/gateway/oauth_proxy.go
  pkg/deploy/gateway/oauth_proxy_test.go
Labels: lgtm, ok-to-test

#1413 fix(helmcharts/stable): It should not be `v2` but `v1` the version of CheCluster in the stable chart.
  helmcharts/stable/Chart.yaml
  helmcharts/stable/README.md
Labels: lgtm

#1414 chore(helmcharts/stable): Remove unused values in values.yaml.
  helmcharts/stable/values.yaml
Labels: lgtm

#1418 feat: Configure the access token timeouts
  api/v2/checluster_types.go
  api/v2/zz_generated.deepcopy.go
  bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml
  config/crd/bases/org.eclipse.che_checlusters.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  pkg/deploy/identity-provider/identity_provider_reconciler.go
  pkg/deploy/identity-provider/identity_provider_reconciler_test.go
  pkg/deploy/identity-provider/identity_provider_util.go
Labels: lgtm

#1421 fix: release script
  .github/workflows/release.yml
Labels: lgtm
