Repository eclipse-che/che-operator, pull requests merged in 2022-12, with the labels that each got.

#1574 chore: Update oauth2-proxy image
  build/scripts/minikube-tests/test-helm.sh
  build/scripts/minikube-tests/test-operator.sh
  build/scripts/minikube-tests/test-upgrade-from-stable-to-next.sh
  build/scripts/minikube-tests/test-upgrade-from-stable-to-stable.sh
  bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/che-operator.Deployment.yaml
  helmcharts/next/templates/che-operator.Deployment.yaml
Labels: lgtm

#1579 Add retry middleware to retry connecting to mainurl if connection failed
  controllers/devworkspace/solver/che_routing.go
  controllers/devworkspace/solver/che_routing_test.go
  pkg/deploy/gateway/traefik_config.go
  pkg/deploy/gateway/traefik_config_util.go
  pkg/deploy/gateway/traefik_config_util_test.go
Labels: lgtm

#1580 feat: Support ephemeral pvc strategy
  api/v2/checluster_types.go
  bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
  config/crd/bases/org.eclipse.che_checlusters.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  pkg/common/constants/constants.go
  pkg/deploy/dev-workspace-config/dev_workspace_config.go
  pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
Labels: lgtm

#1588 fix(utils): whitelist should not cut off second-level domain
  pkg/common/utils/utils.go
  pkg/common/utils/utils_test.go
Labels: lgtm, needs-ok-to-test, ok-to-test

#1587 feat: spec.devEnvironments.podSchedulerName in CR
  api/v2/checluster_types.go
  bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
  config/crd/bases/org.eclipse.che_checlusters.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  pkg/deploy/dev-workspace-config/dev_workspace_config.go
  pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
Labels: lgtm

#1576 feat: configure workspace start timeout from Che Cluster CR
  api/v2/checluster_types.go
  api/v2/zz_generated.deepcopy.go
  bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
  bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml
  config/crd/bases/org.eclipse.che_checlusters.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml
  pkg/common/constants/constants.go
  pkg/deploy/dev-workspace-config/dev_workspace_config.go
  pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
Labels: ok-to-test
