Repository eclipse-che/che-operator, pull requests merged in 2023-01, with the labels that each got.

#1590 fix: Display workspace idle page on k8s
  controllers/devworkspace/solver/che_routing.go
  controllers/devworkspace/solver/che_routing_test.go
Labels: lgtm

#1578 Update GitHub actions to use Node 16 and Ubuntu to latest
  .github/workflows/codecov.yml
  .github/workflows/minikube-test-helm.yaml
  .github/workflows/minikube-test-operator.yaml
  .github/workflows/minikube-test-upgrade-stable-to-next.yaml
  .github/workflows/minikube-test-upgrade-stable-to-stable.yaml
  .github/workflows/pr-check.yml
  .github/workflows/release-che-docs.yml
  .github/workflows/release-chectl.yml
  .github/workflows/release-community-operator-PRs.yml
  .github/workflows/release-helm-charts.yaml
  .github/workflows/release-next-catalog-and-operator-image.yaml
  .github/workflows/release.yml
  .github/workflows/resources-check-main.yml
  .github/workflows/try-in-web-ide.yaml
Labels: needs-ok-to-test

#1596 Set SCC allowPrivilegeEscalation to true when container build enabled
  pkg/common/constants/constants.go
  pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
Labels: lgtm

#1601 chore: Update quay.io/brancz/kube-rbac-proxy from 0.11.0 to 0.13.1
  bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  deploy/deployment/kubernetes/combined.yaml
  deploy/deployment/kubernetes/objects/che-operator.Deployment.yaml
  deploy/deployment/openshift/combined.yaml
  deploy/deployment/openshift/objects/che-operator.Deployment.yaml
  helmcharts/next/templates/che-operator.Deployment.yaml
Labels: lgtm

#1606 fix: set scc priority to null
  Makefile
  bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml
  pkg/deploy/container-build/container_build.go
  pkg/deploy/labels.go
Labels: lgtm

#1608 Cherry-pick commits from #1576 & #1565 & #1606 to 7.58.x
  pkg/common/constants/constants.go
  pkg/deploy/container-build/container_build.go
  pkg/deploy/dev-workspace-config/dev_workspace_config.go
  pkg/deploy/dev-workspace-config/dev_workspace_config_test.go
  pkg/deploy/labels.go
Labels: lgtm, ok-to-test
